site_name: subframe7536

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: #58a8fa
      accent: #0481d4
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: #0481d4
      accent: #58a8fa
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
# Extensions
markdown_extensions:
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - latex.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - roamlinks